USE IBM;

-- CREAR TABLA 
CREATE TABLE Provincias (  
ID CHAR(2) PRIMARY KEY NOT NULL,  
CODER CHAR(3),
Nombre VARCHAR(24) 
);

-- AGREGAR UNA COLUMNA 
ALTER TABLE Provincias ADD COLUMN POBLACIÓN INT(10);

-- MODIFICAR TIPO
ALTER TABLE Provincias MODIFY POBLACIÓN FLOAT(10);

-- ELIMINAR COLUMNA 
ALTER TABLE Provincias DROP COLUMN POBLACIÓN;

-- BORRAR TODOS LOS REGISTROS 
TRUNCATE TABLE Provincias;

-- ELIMINAR TABLA COMPLETA
DROP TABLE Provincias;

